name: setup-node
description: Setup Node.js with npm cache for backend/frontend

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: '24'

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json
