/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IncomesRouteImport } from './routes/incomes'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DriveCallbackRouteImport } from './routes/drive-callback'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomesRoute = IncomesRouteImport.update({
  id: '/incomes',
  path: '/incomes',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveCallbackRoute = DriveCallbackRouteImport.update({
  id: '/drive-callback',
  path: '/drive-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/drive-callback': typeof DriveCallbackRoute
  '/expenses': typeof ExpensesRoute
  '/import': typeof ImportRoute
  '/incomes': typeof IncomesRoute
  '/reports': typeof ReportsRoute
  '/tags': typeof TagsRoute
  '/oauth/callback': typeof OauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/drive-callback': typeof DriveCallbackRoute
  '/expenses': typeof ExpensesRoute
  '/import': typeof ImportRoute
  '/incomes': typeof IncomesRoute
  '/reports': typeof ReportsRoute
  '/tags': typeof TagsRoute
  '/oauth/callback': typeof OauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/drive-callback': typeof DriveCallbackRoute
  '/expenses': typeof ExpensesRoute
  '/import': typeof ImportRoute
  '/incomes': typeof IncomesRoute
  '/reports': typeof ReportsRoute
  '/tags': typeof TagsRoute
  '/oauth/callback': typeof OauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/drive-callback'
    | '/expenses'
    | '/import'
    | '/incomes'
    | '/reports'
    | '/tags'
    | '/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/drive-callback'
    | '/expenses'
    | '/import'
    | '/incomes'
    | '/reports'
    | '/tags'
    | '/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/drive-callback'
    | '/expenses'
    | '/import'
    | '/incomes'
    | '/reports'
    | '/tags'
    | '/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  DriveCallbackRoute: typeof DriveCallbackRoute
  ExpensesRoute: typeof ExpensesRoute
  ImportRoute: typeof ImportRoute
  IncomesRoute: typeof IncomesRoute
  ReportsRoute: typeof ReportsRoute
  TagsRoute: typeof TagsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incomes': {
      id: '/incomes'
      path: '/incomes'
      fullPath: '/incomes'
      preLoaderRoute: typeof IncomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive-callback': {
      id: '/drive-callback'
      path: '/drive-callback'
      fullPath: '/drive-callback'
      preLoaderRoute: typeof DriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  DriveCallbackRoute: DriveCallbackRoute,
  ExpensesRoute: ExpensesRoute,
  ImportRoute: ImportRoute,
  IncomesRoute: IncomesRoute,
  ReportsRoute: ReportsRoute,
  TagsRoute: TagsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
